// Constellation.js  -  Generated by a program written by Don Cross  -  http://cosinekitty.com/

var ConstellationEdgeArray = [
    { 'ConciseName':'UMi', 'DecBottom': 88.0000, 'RaLeft':  0.0000, 'RaRight': 24.0000 }
  , { 'ConciseName':'UMi', 'DecBottom': 86.5000, 'RaLeft':  8.0000, 'RaRight': 14.5000 }
  , { 'ConciseName':'UMi', 'DecBottom': 86.1667, 'RaLeft': 21.0000, 'RaRight': 23.0000 }
  , { 'ConciseName':'UMi', 'DecBottom': 86.0000, 'RaLeft': 18.0000, 'RaRight': 21.0000 }
  , { 'ConciseName':'Cep', 'DecBottom': 85.0000, 'RaLeft':  0.0000, 'RaRight':  8.0000 }
  , { 'ConciseName':'Cam', 'DecBottom': 82.0000, 'RaLeft':  9.1667, 'RaRight': 10.6667 }
  , { 'ConciseName':'Cep', 'DecBottom': 80.0000, 'RaLeft':  0.0000, 'RaRight':  5.0000 }
  , { 'ConciseName':'Cam', 'DecBottom': 80.0000, 'RaLeft': 10.6667, 'RaRight': 14.5000 }
  , { 'ConciseName':'UMi', 'DecBottom': 80.0000, 'RaLeft': 17.5000, 'RaRight': 18.0000 }
  , { 'ConciseName':'Dra', 'DecBottom': 80.0000, 'RaLeft': 20.1667, 'RaRight': 21.0000 }
  , { 'ConciseName':'Cep', 'DecBottom': 77.0000, 'RaLeft':  0.0000, 'RaRight':  3.5083 }
  , { 'ConciseName':'Cam', 'DecBottom': 77.0000, 'RaLeft': 11.5000, 'RaRight': 13.5833 }
  , { 'ConciseName':'UMi', 'DecBottom': 75.0000, 'RaLeft': 16.5333, 'RaRight': 17.5000 }
  , { 'ConciseName':'Cep', 'DecBottom': 75.0000, 'RaLeft': 20.1667, 'RaRight': 20.6667 }
  , { 'ConciseName':'Cam', 'DecBottom': 73.5000, 'RaLeft':  7.9667, 'RaRight':  9.1667 }
  , { 'ConciseName':'Dra', 'DecBottom': 73.5000, 'RaLeft':  9.1667, 'RaRight': 11.3333 }
  , { 'ConciseName':'UMi', 'DecBottom': 70.0000, 'RaLeft': 13.0000, 'RaRight': 16.5333 }
  , { 'ConciseName':'Cas', 'DecBottom': 68.0000, 'RaLeft':  3.1000, 'RaRight':  3.4167 }
  , { 'ConciseName':'Dra', 'DecBottom': 67.0000, 'RaLeft': 20.4167, 'RaRight': 20.6667 }
  , { 'ConciseName':'Dra', 'DecBottom': 66.5000, 'RaLeft': 11.3333, 'RaRight': 12.0000 }
  , { 'ConciseName':'Cep', 'DecBottom': 66.0000, 'RaLeft':  0.0000, 'RaRight':  0.3333 }
  , { 'ConciseName':'UMi', 'DecBottom': 66.0000, 'RaLeft': 14.0000, 'RaRight': 15.6667 }
  , { 'ConciseName':'Cep', 'DecBottom': 66.0000, 'RaLeft': 23.5833, 'RaRight': 24.0000 }
  , { 'ConciseName':'Dra', 'DecBottom': 64.0000, 'RaLeft': 12.0000, 'RaRight': 13.5000 }
  , { 'ConciseName':'Dra', 'DecBottom': 63.0000, 'RaLeft': 13.5000, 'RaRight': 14.4167 }
  , { 'ConciseName':'Cep', 'DecBottom': 63.0000, 'RaLeft': 23.1667, 'RaRight': 23.5833 }
  , { 'ConciseName':'Cam', 'DecBottom': 62.0000, 'RaLeft':  6.1000, 'RaRight':  7.0000 }
  , { 'ConciseName':'Dra', 'DecBottom': 61.5000, 'RaLeft': 20.0000, 'RaRight': 20.4167 }
  , { 'ConciseName':'Cep', 'DecBottom': 60.9167, 'RaLeft': 20.5367, 'RaRight': 20.6000 }
  , { 'ConciseName':'Cam', 'DecBottom': 60.0000, 'RaLeft':  7.0000, 'RaRight':  7.9667 }
  , { 'ConciseName':'UMa', 'DecBottom': 60.0000, 'RaLeft':  7.9667, 'RaRight':  8.4167 }
  , { 'ConciseName':'Dra', 'DecBottom': 59.5000, 'RaLeft': 19.7667, 'RaRight': 20.0000 }
  , { 'ConciseName':'Cep', 'DecBottom': 59.5000, 'RaLeft': 20.0000, 'RaRight': 20.5367 }
  , { 'ConciseName':'Cep', 'DecBottom': 59.0833, 'RaLeft': 22.8667, 'RaRight': 23.1667 }
  , { 'ConciseName':'Cas', 'DecBottom': 58.5000, 'RaLeft':  0.0000, 'RaRight':  2.4333 }
  , { 'ConciseName':'Dra', 'DecBottom': 58.0000, 'RaLeft': 19.4167, 'RaRight': 19.7667 }
  , { 'ConciseName':'Cas', 'DecBottom': 57.5000, 'RaLeft':  1.7000, 'RaRight':  1.9083 }
  , { 'ConciseName':'Cas', 'DecBottom': 57.0000, 'RaLeft':  2.4333, 'RaRight':  3.1000 }
  , { 'ConciseName':'Cam', 'DecBottom': 57.0000, 'RaLeft':  3.1000, 'RaRight':  3.1667 }
  , { 'ConciseName':'Cep', 'DecBottom': 56.2500, 'RaLeft': 22.3167, 'RaRight': 22.8667 }
  , { 'ConciseName':'Cam', 'DecBottom': 56.0000, 'RaLeft':  5.0000, 'RaRight':  6.1000 }
  , { 'ConciseName':'UMa', 'DecBottom': 55.5000, 'RaLeft': 14.0333, 'RaRight': 14.4167 }
  , { 'ConciseName':'Dra', 'DecBottom': 55.5000, 'RaLeft': 14.4167, 'RaRight': 19.4167 }
  , { 'ConciseName':'Cam', 'DecBottom': 55.0000, 'RaLeft':  3.1667, 'RaRight':  3.3333 }
  , { 'ConciseName':'Cep', 'DecBottom': 55.0000, 'RaLeft': 22.1333, 'RaRight': 22.3167 }
  , { 'ConciseName':'Cep', 'DecBottom': 54.8333, 'RaLeft': 20.6000, 'RaRight': 21.9667 }
  , { 'ConciseName':'Cas', 'DecBottom': 54.0000, 'RaLeft':  0.0000, 'RaRight':  1.7000 }
  , { 'ConciseName':'Lyn', 'DecBottom': 54.0000, 'RaLeft':  6.1000, 'RaRight':  6.5000 }
  , { 'ConciseName':'UMa', 'DecBottom': 53.0000, 'RaLeft': 12.0833, 'RaRight': 13.5000 }
  , { 'ConciseName':'Dra', 'DecBottom': 53.0000, 'RaLeft': 15.2500, 'RaRight': 15.7500 }
  , { 'ConciseName':'Cep', 'DecBottom': 52.7500, 'RaLeft': 21.9667, 'RaRight': 22.1333 }
  , { 'ConciseName':'Cam', 'DecBottom': 52.5000, 'RaLeft':  3.3333, 'RaRight':  5.0000 }
  , { 'ConciseName':'Cas', 'DecBottom': 52.5000, 'RaLeft': 22.8667, 'RaRight': 23.3333 }
  , { 'ConciseName':'Dra', 'DecBottom': 51.5000, 'RaLeft': 15.7500, 'RaRight': 17.0000 }
  , { 'ConciseName':'Per', 'DecBottom': 50.5000, 'RaLeft':  2.0417, 'RaRight':  2.5167 }
  , { 'ConciseName':'Dra', 'DecBottom': 50.5000, 'RaLeft': 17.0000, 'RaRight': 18.2333 }
  , { 'ConciseName':'Cas', 'DecBottom': 50.0000, 'RaLeft':  0.0000, 'RaRight':  1.3667 }
  , { 'ConciseName':'Per', 'DecBottom': 50.0000, 'RaLeft':  1.3667, 'RaRight':  1.6667 }
  , { 'ConciseName':'Lyn', 'DecBottom': 50.0000, 'RaLeft':  6.5000, 'RaRight':  6.8000 }
  , { 'ConciseName':'Cas', 'DecBottom': 50.0000, 'RaLeft': 23.3333, 'RaRight': 24.0000 }
  , { 'ConciseName':'UMa', 'DecBottom': 48.5000, 'RaLeft': 13.5000, 'RaRight': 14.0333 }
  , { 'ConciseName':'Cas', 'DecBottom': 48.0000, 'RaLeft':  0.0000, 'RaRight':  1.1167 }
  , { 'ConciseName':'Cas', 'DecBottom': 48.0000, 'RaLeft': 23.5833, 'RaRight': 24.0000 }
  , { 'ConciseName':'Her', 'DecBottom': 47.5000, 'RaLeft': 18.1750, 'RaRight': 18.2333 }
  , { 'ConciseName':'Dra', 'DecBottom': 47.5000, 'RaLeft': 18.2333, 'RaRight': 19.0833 }
  , { 'ConciseName':'Cyg', 'DecBottom': 47.5000, 'RaLeft': 19.0833, 'RaRight': 19.1667 }
  , { 'ConciseName':'Per', 'DecBottom': 47.0000, 'RaLeft':  1.6667, 'RaRight':  2.0417 }
  , { 'ConciseName':'UMa', 'DecBottom': 47.0000, 'RaLeft':  8.4167, 'RaRight':  9.1667 }
  , { 'ConciseName':'Cas', 'DecBottom': 46.0000, 'RaLeft':  0.1667, 'RaRight':  0.8667 }
  , { 'ConciseName':'UMa', 'DecBottom': 45.0000, 'RaLeft': 12.0000, 'RaRight': 12.0833 }
  , { 'ConciseName':'Lyn', 'DecBottom': 44.5000, 'RaLeft':  6.8000, 'RaRight':  7.3667 }
  , { 'ConciseName':'Cyg', 'DecBottom': 44.0000, 'RaLeft': 21.9083, 'RaRight': 21.9667 }
  , { 'ConciseName':'Cyg', 'DecBottom': 43.7500, 'RaLeft': 21.8750, 'RaRight': 21.9083 }
  , { 'ConciseName':'Cyg', 'DecBottom': 43.5000, 'RaLeft': 19.1667, 'RaRight': 19.4000 }
  , { 'ConciseName':'UMa', 'DecBottom': 42.0000, 'RaLeft':  9.1667, 'RaRight': 10.1667 }
  , { 'ConciseName':'UMa', 'DecBottom': 40.0000, 'RaLeft': 10.1667, 'RaRight': 10.7833 }
  , { 'ConciseName':'Boo', 'DecBottom': 40.0000, 'RaLeft': 15.4333, 'RaRight': 15.7500 }
  , { 'ConciseName':'Her', 'DecBottom': 40.0000, 'RaLeft': 15.7500, 'RaRight': 16.3333 }
  , { 'ConciseName':'Lyn', 'DecBottom': 39.7500, 'RaLeft':  9.2500, 'RaRight':  9.5833 }
  , { 'ConciseName':'And', 'DecBottom': 36.7500, 'RaLeft':  0.0000, 'RaRight':  2.5167 }
  , { 'ConciseName':'Per', 'DecBottom': 36.7500, 'RaLeft':  2.5167, 'RaRight':  2.5667 }
  , { 'ConciseName':'Lyr', 'DecBottom': 36.5000, 'RaLeft': 19.3583, 'RaRight': 19.4000 }
  , { 'ConciseName':'Per', 'DecBottom': 36.0000, 'RaLeft':  4.5000, 'RaRight':  4.6917 }
  , { 'ConciseName':'Cyg', 'DecBottom': 36.0000, 'RaLeft': 21.7333, 'RaRight': 21.8750 }
  , { 'ConciseName':'Lac', 'DecBottom': 36.0000, 'RaLeft': 21.8750, 'RaRight': 22.0000 }
  , { 'ConciseName':'Aur', 'DecBottom': 35.5000, 'RaLeft':  6.5333, 'RaRight':  7.3667 }
  , { 'ConciseName':'Lyn', 'DecBottom': 35.5000, 'RaLeft':  7.3667, 'RaRight':  7.7500 }
  , { 'ConciseName':'And', 'DecBottom': 35.0000, 'RaLeft':  0.0000, 'RaRight':  2.0000 }
  , { 'ConciseName':'Lac', 'DecBottom': 35.0000, 'RaLeft': 22.0000, 'RaRight': 22.8167 }
  , { 'ConciseName':'Lac', 'DecBottom': 34.5000, 'RaLeft': 22.8167, 'RaRight': 22.8667 }
  , { 'ConciseName':'And', 'DecBottom': 34.5000, 'RaLeft': 22.8667, 'RaRight': 23.5000 }
  , { 'ConciseName':'Per', 'DecBottom': 34.0000, 'RaLeft':  2.5667, 'RaRight':  2.7167 }
  , { 'ConciseName':'UMa', 'DecBottom': 34.0000, 'RaLeft': 10.7833, 'RaRight': 11.0000 }
  , { 'ConciseName':'CVn', 'DecBottom': 34.0000, 'RaLeft': 12.0000, 'RaRight': 12.3333 }
  , { 'ConciseName':'Lyn', 'DecBottom': 33.5000, 'RaLeft':  7.7500, 'RaRight':  9.2500 }
  , { 'ConciseName':'LMi', 'DecBottom': 33.5000, 'RaLeft':  9.2500, 'RaRight':  9.8833 }
  , { 'ConciseName':'And', 'DecBottom': 33.0000, 'RaLeft':  0.7167, 'RaRight':  1.4083 }
  , { 'ConciseName':'Boo', 'DecBottom': 33.0000, 'RaLeft': 15.1833, 'RaRight': 15.4333 }
  , { 'ConciseName':'And', 'DecBottom': 32.0833, 'RaLeft': 23.5000, 'RaRight': 23.7500 }
  , { 'ConciseName':'CVn', 'DecBottom': 32.0000, 'RaLeft': 12.3333, 'RaRight': 13.2500 }
  , { 'ConciseName':'And', 'DecBottom': 31.3333, 'RaLeft': 23.7500, 'RaRight': 24.0000 }
  , { 'ConciseName':'CVn', 'DecBottom': 30.7500, 'RaLeft': 13.9583, 'RaRight': 14.0333 }
  , { 'ConciseName':'Tri', 'DecBottom': 30.6667, 'RaLeft':  2.4167, 'RaRight':  2.7167 }
  , { 'ConciseName':'Per', 'DecBottom': 30.6667, 'RaLeft':  2.7167, 'RaRight':  4.5000 }
  , { 'ConciseName':'Aur', 'DecBottom': 30.0000, 'RaLeft':  4.5000, 'RaRight':  4.7500 }
  , { 'ConciseName':'Lyr', 'DecBottom': 30.0000, 'RaLeft': 18.1750, 'RaRight': 19.3583 }
  , { 'ConciseName':'UMa', 'DecBottom': 29.0000, 'RaLeft': 11.0000, 'RaRight': 12.0000 }
  , { 'ConciseName':'Cyg', 'DecBottom': 29.0000, 'RaLeft': 19.6667, 'RaRight': 20.9167 }
  , { 'ConciseName':'Aur', 'DecBottom': 28.5000, 'RaLeft':  4.7500, 'RaRight':  5.8833 }
  , { 'ConciseName':'LMi', 'DecBottom': 28.5000, 'RaLeft':  9.8833, 'RaRight': 10.5000 }
  , { 'ConciseName':'CVn', 'DecBottom': 28.5000, 'RaLeft': 13.2500, 'RaRight': 13.9583 }
  , { 'ConciseName':'And', 'DecBottom': 28.0000, 'RaLeft':  0.0000, 'RaRight':  0.0667 }
  , { 'ConciseName':'Tri', 'DecBottom': 28.0000, 'RaLeft':  1.4083, 'RaRight':  1.6667 }
  , { 'ConciseName':'Aur', 'DecBottom': 28.0000, 'RaLeft':  5.8833, 'RaRight':  6.5333 }
  , { 'ConciseName':'Gem', 'DecBottom': 28.0000, 'RaLeft':  7.8833, 'RaRight':  8.0000 }
  , { 'ConciseName':'Cyg', 'DecBottom': 28.0000, 'RaLeft': 20.9167, 'RaRight': 21.7333 }
  , { 'ConciseName':'Cyg', 'DecBottom': 27.5000, 'RaLeft': 19.2583, 'RaRight': 19.6667 }
  , { 'ConciseName':'Tri', 'DecBottom': 27.2500, 'RaLeft':  1.9167, 'RaRight':  2.4167 }
  , { 'ConciseName':'CrB', 'DecBottom': 27.0000, 'RaLeft': 16.1667, 'RaRight': 16.3333 }
  , { 'ConciseName':'Boo', 'DecBottom': 26.0000, 'RaLeft': 15.0833, 'RaRight': 15.1833 }
  , { 'ConciseName':'CrB', 'DecBottom': 26.0000, 'RaLeft': 15.1833, 'RaRight': 16.1667 }
  , { 'ConciseName':'Lyr', 'DecBottom': 26.0000, 'RaLeft': 18.3667, 'RaRight': 18.8667 }
  , { 'ConciseName':'LMi', 'DecBottom': 25.5000, 'RaLeft': 10.7500, 'RaRight': 11.0000 }
  , { 'ConciseName':'Lyr', 'DecBottom': 25.5000, 'RaLeft': 18.8667, 'RaRight': 19.2583 }
  , { 'ConciseName':'Tri', 'DecBottom': 25.0000, 'RaLeft':  1.6667, 'RaRight':  1.9167 }
  , { 'ConciseName':'Psc', 'DecBottom': 23.7500, 'RaLeft':  0.7167, 'RaRight':  0.8500 }
  , { 'ConciseName':'LMi', 'DecBottom': 23.5000, 'RaLeft': 10.5000, 'RaRight': 10.7500 }
  , { 'ConciseName':'Vul', 'DecBottom': 23.5000, 'RaLeft': 21.2500, 'RaRight': 21.4167 }
  , { 'ConciseName':'Tau', 'DecBottom': 22.8333, 'RaLeft':  5.7000, 'RaRight':  5.8833 }
  , { 'ConciseName':'And', 'DecBottom': 22.0000, 'RaLeft':  0.0667, 'RaRight':  0.1417 }
  , { 'ConciseName':'Ser', 'DecBottom': 22.0000, 'RaLeft': 15.9167, 'RaRight': 16.0333 }
  , { 'ConciseName':'Gem', 'DecBottom': 21.5000, 'RaLeft':  5.8833, 'RaRight':  6.2167 }
  , { 'ConciseName':'Vul', 'DecBottom': 21.2500, 'RaLeft': 19.8333, 'RaRight': 20.2500 }
  , { 'ConciseName':'Vul', 'DecBottom': 21.0833, 'RaLeft': 18.8667, 'RaRight': 19.2500 }
  , { 'ConciseName':'And', 'DecBottom': 21.0000, 'RaLeft':  0.1417, 'RaRight':  0.8500 }
  , { 'ConciseName':'Vul', 'DecBottom': 20.5000, 'RaLeft': 20.2500, 'RaRight': 20.5667 }
  , { 'ConciseName':'Gem', 'DecBottom': 20.0000, 'RaLeft':  7.8083, 'RaRight':  7.8833 }
  , { 'ConciseName':'Vul', 'DecBottom': 19.5000, 'RaLeft': 20.5667, 'RaRight': 21.2500 }
  , { 'ConciseName':'Vul', 'DecBottom': 19.1667, 'RaLeft': 19.2500, 'RaRight': 19.8333 }
  , { 'ConciseName':'Ari', 'DecBottom': 19.0000, 'RaLeft':  3.2833, 'RaRight':  3.3667 }
  , { 'ConciseName':'Sge', 'DecBottom': 18.5000, 'RaLeft': 18.8667, 'RaRight': 19.0000 }
  , { 'ConciseName':'Ori', 'DecBottom': 18.0000, 'RaLeft':  5.7000, 'RaRight':  5.7667 }
  , { 'ConciseName':'Gem', 'DecBottom': 17.5000, 'RaLeft':  6.2167, 'RaRight':  6.3083 }
  , { 'ConciseName':'Sge', 'DecBottom': 16.1667, 'RaLeft': 19.0000, 'RaRight': 19.8333 }
  , { 'ConciseName':'Tau', 'DecBottom': 16.0000, 'RaLeft':  4.9667, 'RaRight':  5.3333 }
  , { 'ConciseName':'Her', 'DecBottom': 16.0000, 'RaLeft': 15.9167, 'RaRight': 16.0833 }
  , { 'ConciseName':'Sge', 'DecBottom': 15.7500, 'RaLeft': 19.8333, 'RaRight': 20.2500 }
  , { 'ConciseName':'Tau', 'DecBottom': 15.5000, 'RaLeft':  4.6167, 'RaRight':  4.9667 }
  , { 'ConciseName':'Tau', 'DecBottom': 15.5000, 'RaLeft':  5.3333, 'RaRight':  5.6000 }
  , { 'ConciseName':'Com', 'DecBottom': 15.0000, 'RaLeft': 12.8333, 'RaRight': 13.5000 }
  , { 'ConciseName':'Her', 'DecBottom': 14.3333, 'RaLeft': 17.2500, 'RaRight': 18.2500 }
  , { 'ConciseName':'Com', 'DecBottom': 14.0000, 'RaLeft': 11.8667, 'RaRight': 12.8333 }
  , { 'ConciseName':'Gem', 'DecBottom': 13.5000, 'RaLeft':  7.5000, 'RaRight':  7.8083 }
  , { 'ConciseName':'Her', 'DecBottom': 12.8333, 'RaLeft': 16.7500, 'RaRight': 17.2500 }
  , { 'ConciseName':'Peg', 'DecBottom': 12.5000, 'RaLeft':  0.0000, 'RaRight':  0.1417 }
  , { 'ConciseName':'Tau', 'DecBottom': 12.5000, 'RaLeft':  5.6000, 'RaRight':  5.7667 }
  , { 'ConciseName':'Gem', 'DecBottom': 12.5000, 'RaLeft':  7.0000, 'RaRight':  7.5000 }
  , { 'ConciseName':'Peg', 'DecBottom': 12.5000, 'RaLeft': 21.1167, 'RaRight': 21.3333 }
  , { 'ConciseName':'Gem', 'DecBottom': 12.0000, 'RaLeft':  6.3083, 'RaRight':  6.9333 }
  , { 'ConciseName':'Her', 'DecBottom': 12.0000, 'RaLeft': 18.2500, 'RaRight': 18.8667 }
  , { 'ConciseName':'Del', 'DecBottom': 11.8333, 'RaLeft': 20.8750, 'RaRight': 21.0500 }
  , { 'ConciseName':'Peg', 'DecBottom': 11.8333, 'RaLeft': 21.0500, 'RaRight': 21.1167 }
  , { 'ConciseName':'Leo', 'DecBottom': 11.0000, 'RaLeft': 11.5167, 'RaRight': 11.8667 }
  , { 'ConciseName':'Ori', 'DecBottom': 10.0000, 'RaLeft':  6.2417, 'RaRight':  6.3083 }
  , { 'ConciseName':'Gem', 'DecBottom': 10.0000, 'RaLeft':  6.9333, 'RaRight':  7.0000 }
  , { 'ConciseName':'Cnc', 'DecBottom': 10.0000, 'RaLeft':  7.8083, 'RaRight':  7.9250 }
  , { 'ConciseName':'Peg', 'DecBottom': 10.0000, 'RaLeft': 23.8333, 'RaRight': 24.0000 }
  , { 'ConciseName':'Ari', 'DecBottom':  9.9167, 'RaLeft':  1.6667, 'RaRight':  3.2833 }
  , { 'ConciseName':'Del', 'DecBottom':  8.5000, 'RaLeft': 20.1417, 'RaRight': 20.3000 }
  , { 'ConciseName':'Boo', 'DecBottom':  8.0000, 'RaLeft': 13.5000, 'RaRight': 15.0833 }
  , { 'ConciseName':'Peg', 'DecBottom':  7.5000, 'RaLeft': 22.7500, 'RaRight': 23.8333 }
  , { 'ConciseName':'Cnc', 'DecBottom':  7.0000, 'RaLeft':  7.9250, 'RaRight':  9.2500 }
  , { 'ConciseName':'Leo', 'DecBottom':  7.0000, 'RaLeft':  9.2500, 'RaRight': 10.7500 }
  , { 'ConciseName':'Oph', 'DecBottom':  6.2500, 'RaLeft': 18.2500, 'RaRight': 18.6622 }
  , { 'ConciseName':'Aql', 'DecBottom':  6.2500, 'RaLeft': 18.6622, 'RaRight': 18.8667 }
  , { 'ConciseName':'Del', 'DecBottom':  6.0000, 'RaLeft': 20.8333, 'RaRight': 20.8750 }
  , { 'ConciseName':'CMi', 'DecBottom':  5.5000, 'RaLeft':  7.0000, 'RaRight':  7.0167 }
  , { 'ConciseName':'Ser', 'DecBottom':  4.5000, 'RaLeft': 18.2500, 'RaRight': 18.4250 }
  , { 'ConciseName':'Her', 'DecBottom':  4.0000, 'RaLeft': 16.0833, 'RaRight': 16.7500 }
  , { 'ConciseName':'Oph', 'DecBottom':  3.0000, 'RaLeft': 18.2500, 'RaRight': 18.4250 }
  , { 'ConciseName':'Peg', 'DecBottom':  2.7500, 'RaLeft': 21.4667, 'RaRight': 21.6667 }
  , { 'ConciseName':'Psc', 'DecBottom':  2.0000, 'RaLeft':  0.0000, 'RaRight':  2.0000 }
  , { 'ConciseName':'Ser', 'DecBottom':  2.0000, 'RaLeft': 18.5833, 'RaRight': 18.8667 }
  , { 'ConciseName':'Del', 'DecBottom':  2.0000, 'RaLeft': 20.3000, 'RaRight': 20.8333 }
  , { 'ConciseName':'Equ', 'DecBottom':  2.0000, 'RaLeft': 20.8333, 'RaRight': 21.3333 }
  , { 'ConciseName':'Peg', 'DecBottom':  2.0000, 'RaLeft': 21.3333, 'RaRight': 21.4667 }
  , { 'ConciseName':'Peg', 'DecBottom':  2.0000, 'RaLeft': 22.0000, 'RaRight': 22.7500 }
  , { 'ConciseName':'Peg', 'DecBottom':  1.7500, 'RaLeft': 21.6667, 'RaRight': 22.0000 }
  , { 'ConciseName':'CMi', 'DecBottom':  1.5000, 'RaLeft':  7.0167, 'RaRight':  7.2000 }
  , { 'ConciseName':'Tau', 'DecBottom':  0.0000, 'RaLeft':  3.5833, 'RaRight':  4.6167 }
  , { 'ConciseName':'Ori', 'DecBottom':  0.0000, 'RaLeft':  4.6167, 'RaRight':  4.6667 }
  , { 'ConciseName':'CMi', 'DecBottom':  0.0000, 'RaLeft':  7.2000, 'RaRight':  8.0833 }
  , { 'ConciseName':'Vir', 'DecBottom':  0.0000, 'RaLeft': 14.6667, 'RaRight': 15.0833 }
  , { 'ConciseName':'Oph', 'DecBottom':  0.0000, 'RaLeft': 17.8333, 'RaRight': 18.2500 }
  , { 'ConciseName':'Cet', 'DecBottom': -1.7500, 'RaLeft':  2.6500, 'RaRight':  3.2833 }
  , { 'ConciseName':'Tau', 'DecBottom': -1.7500, 'RaLeft':  3.2833, 'RaRight':  3.5833 }
  , { 'ConciseName':'Ser', 'DecBottom': -3.2500, 'RaLeft': 15.0833, 'RaRight': 16.2667 }
  , { 'ConciseName':'Ori', 'DecBottom': -4.0000, 'RaLeft':  4.6667, 'RaRight':  5.0833 }
  , { 'ConciseName':'Ori', 'DecBottom': -4.0000, 'RaLeft':  5.8333, 'RaRight':  6.2417 }
  , { 'ConciseName':'Ser', 'DecBottom': -4.0000, 'RaLeft': 17.8333, 'RaRight': 17.9667 }
  , { 'ConciseName':'Ser', 'DecBottom': -4.0000, 'RaLeft': 18.2500, 'RaRight': 18.5833 }
  , { 'ConciseName':'Aql', 'DecBottom': -4.0000, 'RaLeft': 18.5833, 'RaRight': 18.8667 }
  , { 'ConciseName':'Psc', 'DecBottom': -4.0000, 'RaLeft': 22.7500, 'RaRight': 23.8333 }
  , { 'ConciseName':'Leo', 'DecBottom': -6.0000, 'RaLeft': 10.7500, 'RaRight': 11.5167 }
  , { 'ConciseName':'Vir', 'DecBottom': -6.0000, 'RaLeft': 11.5167, 'RaRight': 11.8333 }
  , { 'ConciseName':'Psc', 'DecBottom': -7.0000, 'RaLeft':  0.0000, 'RaRight':  0.3333 }
  , { 'ConciseName':'Psc', 'DecBottom': -7.0000, 'RaLeft': 23.8333, 'RaRight': 24.0000 }
  , { 'ConciseName':'Vir', 'DecBottom': -8.0000, 'RaLeft': 14.2500, 'RaRight': 14.6667 }
  , { 'ConciseName':'Oph', 'DecBottom': -8.0000, 'RaLeft': 15.9167, 'RaRight': 16.2667 }
  , { 'ConciseName':'Aql', 'DecBottom': -9.0000, 'RaLeft': 20.0000, 'RaRight': 20.5333 }
  , { 'ConciseName':'Aqr', 'DecBottom': -9.0000, 'RaLeft': 21.3333, 'RaRight': 21.8667 }
  , { 'ConciseName':'Oph', 'DecBottom':-10.0000, 'RaLeft': 17.1667, 'RaRight': 17.9667 }
  , { 'ConciseName':'Mon', 'DecBottom':-11.0000, 'RaLeft':  5.8333, 'RaRight':  8.0833 }
  , { 'ConciseName':'Eri', 'DecBottom':-11.0000, 'RaLeft':  4.9167, 'RaRight':  5.0833 }
  , { 'ConciseName':'Ori', 'DecBottom':-11.0000, 'RaLeft':  5.0833, 'RaRight':  5.8333 }
  , { 'ConciseName':'Hya', 'DecBottom':-11.0000, 'RaLeft':  8.0833, 'RaRight':  8.3667 }
  , { 'ConciseName':'Sex', 'DecBottom':-11.0000, 'RaLeft':  9.5833, 'RaRight': 10.7500 }
  , { 'ConciseName':'Vir', 'DecBottom':-11.0000, 'RaLeft': 11.8333, 'RaRight': 12.8333 }
  , { 'ConciseName':'Oph', 'DecBottom':-11.6667, 'RaLeft': 17.5833, 'RaRight': 17.6667 }
  , { 'ConciseName':'Aql', 'DecBottom':-12.0333, 'RaLeft': 18.8667, 'RaRight': 20.0000 }
  , { 'ConciseName':'Eri', 'DecBottom':-14.5000, 'RaLeft':  4.8333, 'RaRight':  4.9167 }
  , { 'ConciseName':'Aqr', 'DecBottom':-15.0000, 'RaLeft': 20.5333, 'RaRight': 21.3333 }
  , { 'ConciseName':'Ser', 'DecBottom':-16.0000, 'RaLeft': 17.1667, 'RaRight': 18.2500 }
  , { 'ConciseName':'Sct', 'DecBottom':-16.0000, 'RaLeft': 18.2500, 'RaRight': 18.8667 }
  , { 'ConciseName':'Hya', 'DecBottom':-17.0000, 'RaLeft':  8.3667, 'RaRight':  8.5833 }
  , { 'ConciseName':'Oph', 'DecBottom':-18.2500, 'RaLeft': 16.2667, 'RaRight': 16.3750 }
  , { 'ConciseName':'Hya', 'DecBottom':-19.0000, 'RaLeft':  8.5833, 'RaRight':  9.0833 }
  , { 'ConciseName':'Crt', 'DecBottom':-19.0000, 'RaLeft': 10.7500, 'RaRight': 10.8333 }
  , { 'ConciseName':'Sco', 'DecBottom':-19.2500, 'RaLeft': 16.2667, 'RaRight': 16.3750 }
  , { 'ConciseName':'Lib', 'DecBottom':-20.0000, 'RaLeft': 15.6667, 'RaRight': 15.9167 }
  , { 'ConciseName':'Crv', 'DecBottom':-22.0000, 'RaLeft': 12.5833, 'RaRight': 12.8333 }
  , { 'ConciseName':'Vir', 'DecBottom':-22.0000, 'RaLeft': 12.8333, 'RaRight': 14.2500 }
  , { 'ConciseName':'Hya', 'DecBottom':-24.0000, 'RaLeft':  9.0833, 'RaRight':  9.7500 }
  , { 'ConciseName':'Cet', 'DecBottom':-24.3833, 'RaLeft':  1.6667, 'RaRight':  2.6500 }
  , { 'ConciseName':'Eri', 'DecBottom':-24.3833, 'RaLeft':  2.6500, 'RaRight':  3.7500 }
  , { 'ConciseName':'Crt', 'DecBottom':-24.5000, 'RaLeft': 10.8333, 'RaRight': 11.8333 }
  , { 'ConciseName':'Crv', 'DecBottom':-24.5000, 'RaLeft': 11.8333, 'RaRight': 12.5833 }
  , { 'ConciseName':'Lib', 'DecBottom':-24.5000, 'RaLeft': 14.2500, 'RaRight': 14.9167 }
  , { 'ConciseName':'Oph', 'DecBottom':-24.5833, 'RaLeft': 16.2667, 'RaRight': 16.7500 }
  , { 'ConciseName':'Cet', 'DecBottom':-25.5000, 'RaLeft':  0.0000, 'RaRight':  1.6667 }
  , { 'ConciseName':'Cap', 'DecBottom':-25.5000, 'RaLeft': 21.3333, 'RaRight': 21.8667 }
  , { 'ConciseName':'Aqr', 'DecBottom':-25.5000, 'RaLeft': 21.8667, 'RaRight': 23.8333 }
  , { 'ConciseName':'Cet', 'DecBottom':-25.5000, 'RaLeft': 23.8333, 'RaRight': 24.0000 }
  , { 'ConciseName':'Hya', 'DecBottom':-26.5000, 'RaLeft':  9.7500, 'RaRight': 10.2500 }
  , { 'ConciseName':'Eri', 'DecBottom':-27.2500, 'RaLeft':  4.7000, 'RaRight':  4.8333 }
  , { 'ConciseName':'Lep', 'DecBottom':-27.2500, 'RaLeft':  4.8333, 'RaRight':  6.1167 }
  , { 'ConciseName':'Cap', 'DecBottom':-28.0000, 'RaLeft': 20.0000, 'RaRight': 21.3333 }
  , { 'ConciseName':'Hya', 'DecBottom':-29.1667, 'RaLeft': 10.2500, 'RaRight': 10.5833 }
  , { 'ConciseName':'Hya', 'DecBottom':-29.5000, 'RaLeft': 12.5833, 'RaRight': 14.9167 }
  , { 'ConciseName':'Lib', 'DecBottom':-29.5000, 'RaLeft': 14.9167, 'RaRight': 15.6667 }
  , { 'ConciseName':'Sco', 'DecBottom':-29.5000, 'RaLeft': 15.6667, 'RaRight': 16.0000 }
  , { 'ConciseName':'Eri', 'DecBottom':-30.0000, 'RaLeft':  4.5833, 'RaRight':  4.7000 }
  , { 'ConciseName':'Oph', 'DecBottom':-30.0000, 'RaLeft': 16.7500, 'RaRight': 17.6000 }
  , { 'ConciseName':'Sgr', 'DecBottom':-30.0000, 'RaLeft': 17.6000, 'RaRight': 17.8333 }
  , { 'ConciseName':'Hya', 'DecBottom':-31.1667, 'RaLeft': 10.5833, 'RaRight': 10.8333 }
  , { 'ConciseName':'CMa', 'DecBottom':-33.0000, 'RaLeft':  6.1167, 'RaRight':  7.3667 }
  , { 'ConciseName':'Hya', 'DecBottom':-33.0000, 'RaLeft': 12.2500, 'RaRight': 12.5833 }
  , { 'ConciseName':'Hya', 'DecBottom':-35.0000, 'RaLeft': 10.8333, 'RaRight': 12.2500 }
  , { 'ConciseName':'For', 'DecBottom':-36.0000, 'RaLeft':  3.5000, 'RaRight':  3.7500 }
  , { 'ConciseName':'Pyx', 'DecBottom':-36.7500, 'RaLeft':  8.3667, 'RaRight':  9.3667 }
  , { 'ConciseName':'Eri', 'DecBottom':-37.0000, 'RaLeft':  4.2667, 'RaRight':  4.5833 }
  , { 'ConciseName':'Sgr', 'DecBottom':-37.0000, 'RaLeft': 17.8333, 'RaRight': 19.1667 }
  , { 'ConciseName':'PsA', 'DecBottom':-37.0000, 'RaLeft': 21.3333, 'RaRight': 23.0000 }
  , { 'ConciseName':'Scl', 'DecBottom':-37.0000, 'RaLeft': 23.0000, 'RaRight': 23.3333 }
  , { 'ConciseName':'For', 'DecBottom':-39.5833, 'RaLeft':  3.0000, 'RaRight':  3.5000 }
  , { 'ConciseName':'Ant', 'DecBottom':-39.7500, 'RaLeft':  9.3667, 'RaRight': 11.0000 }
  , { 'ConciseName':'Scl', 'DecBottom':-40.0000, 'RaLeft':  0.0000, 'RaRight':  1.6667 }
  , { 'ConciseName':'For', 'DecBottom':-40.0000, 'RaLeft':  1.6667, 'RaRight':  3.0000 }
  , { 'ConciseName':'Eri', 'DecBottom':-40.0000, 'RaLeft':  3.8667, 'RaRight':  4.2667 }
  , { 'ConciseName':'Scl', 'DecBottom':-40.0000, 'RaLeft': 23.3333, 'RaRight': 24.0000 }
  , { 'ConciseName':'Cen', 'DecBottom':-42.0000, 'RaLeft': 14.1667, 'RaRight': 14.9167 }
  , { 'ConciseName':'Lup', 'DecBottom':-42.0000, 'RaLeft': 15.6667, 'RaRight': 16.0000 }
  , { 'ConciseName':'Sco', 'DecBottom':-42.0000, 'RaLeft': 16.0000, 'RaRight': 16.4208 }
  , { 'ConciseName':'Cae', 'DecBottom':-43.0000, 'RaLeft':  4.8333, 'RaRight':  5.0000 }
  , { 'ConciseName':'Col', 'DecBottom':-43.0000, 'RaLeft':  5.0000, 'RaRight':  6.5833 }
  , { 'ConciseName':'Pup', 'DecBottom':-43.0000, 'RaLeft':  8.0000, 'RaRight':  8.3667 }
  , { 'ConciseName':'Eri', 'DecBottom':-44.0000, 'RaLeft':  3.4167, 'RaRight':  3.8667 }
  , { 'ConciseName':'Sco', 'DecBottom':-45.5000, 'RaLeft': 16.4208, 'RaRight': 17.8333 }
  , { 'ConciseName':'CrA', 'DecBottom':-45.5000, 'RaLeft': 17.8333, 'RaRight': 19.1667 }
  , { 'ConciseName':'Sgr', 'DecBottom':-45.5000, 'RaLeft': 19.1667, 'RaRight': 20.3333 }
  , { 'ConciseName':'Mic', 'DecBottom':-45.5000, 'RaLeft': 20.3333, 'RaRight': 21.3333 }
  , { 'ConciseName':'Eri', 'DecBottom':-46.0000, 'RaLeft':  3.0000, 'RaRight':  3.4167 }
  , { 'ConciseName':'Cae', 'DecBottom':-46.5000, 'RaLeft':  4.5000, 'RaRight':  4.8333 }
  , { 'ConciseName':'Lup', 'DecBottom':-48.0000, 'RaLeft': 15.3333, 'RaRight': 15.6667 }
  , { 'ConciseName':'Phe', 'DecBottom':-48.1667, 'RaLeft':  0.0000, 'RaRight':  2.3333 }
  , { 'ConciseName':'Eri', 'DecBottom':-49.0000, 'RaLeft':  2.6667, 'RaRight':  3.0000 }
  , { 'ConciseName':'Hor', 'DecBottom':-49.0000, 'RaLeft':  4.0833, 'RaRight':  4.2667 }
  , { 'ConciseName':'Cae', 'DecBottom':-49.0000, 'RaLeft':  4.2667, 'RaRight':  4.5000 }
  , { 'ConciseName':'Gru', 'DecBottom':-50.0000, 'RaLeft': 21.3333, 'RaRight': 22.0000 }
  , { 'ConciseName':'Pup', 'DecBottom':-50.7500, 'RaLeft':  6.0000, 'RaRight':  8.0000 }
  , { 'ConciseName':'Vel', 'DecBottom':-50.7500, 'RaLeft':  8.0000, 'RaRight':  8.1667 }
  , { 'ConciseName':'Eri', 'DecBottom':-51.0000, 'RaLeft':  2.4167, 'RaRight':  2.6667 }
  , { 'ConciseName':'Hor', 'DecBottom':-51.0000, 'RaLeft':  3.8333, 'RaRight':  4.0833 }
  , { 'ConciseName':'Phe', 'DecBottom':-51.5000, 'RaLeft':  0.0000, 'RaRight':  1.8333 }
  , { 'ConciseName':'Car', 'DecBottom':-52.5000, 'RaLeft':  6.0000, 'RaRight':  6.1667 }
  , { 'ConciseName':'Vel', 'DecBottom':-53.0000, 'RaLeft':  8.1667, 'RaRight':  8.4500 }
  , { 'ConciseName':'Hor', 'DecBottom':-53.1667, 'RaLeft':  3.5000, 'RaRight':  3.8333 }
  , { 'ConciseName':'Dor', 'DecBottom':-53.1667, 'RaLeft':  3.8333, 'RaRight':  4.0000 }
  , { 'ConciseName':'Phe', 'DecBottom':-53.5000, 'RaLeft':  0.0000, 'RaRight':  1.5833 }
  , { 'ConciseName':'Eri', 'DecBottom':-54.0000, 'RaLeft':  2.1667, 'RaRight':  2.4167 }
  , { 'ConciseName':'Pic', 'DecBottom':-54.0000, 'RaLeft':  4.5000, 'RaRight':  5.0000 }
  , { 'ConciseName':'Lup', 'DecBottom':-54.0000, 'RaLeft': 15.0500, 'RaRight': 15.3333 }
  , { 'ConciseName':'Vel', 'DecBottom':-54.5000, 'RaLeft':  8.4500, 'RaRight':  8.8333 }
  , { 'ConciseName':'Car', 'DecBottom':-55.0000, 'RaLeft':  6.1667, 'RaRight':  6.5000 }
  , { 'ConciseName':'Cen', 'DecBottom':-55.0000, 'RaLeft': 11.8333, 'RaRight': 12.8333 }
  , { 'ConciseName':'Lup', 'DecBottom':-55.0000, 'RaLeft': 14.1667, 'RaRight': 15.0500 }
  , { 'ConciseName':'Nor', 'DecBottom':-55.0000, 'RaLeft': 15.0500, 'RaRight': 15.3333 }
  , { 'ConciseName':'Dor', 'DecBottom':-56.5000, 'RaLeft':  4.0000, 'RaRight':  4.3333 }
  , { 'ConciseName':'Vel', 'DecBottom':-56.5000, 'RaLeft':  8.8333, 'RaRight': 11.0000 }
  , { 'ConciseName':'Cen', 'DecBottom':-56.5000, 'RaLeft': 11.0000, 'RaRight': 11.2500 }
  , { 'ConciseName':'Ara', 'DecBottom':-57.0000, 'RaLeft': 17.5000, 'RaRight': 18.0000 }
  , { 'ConciseName':'Tel', 'DecBottom':-57.0000, 'RaLeft': 18.0000, 'RaRight': 20.3333 }
  , { 'ConciseName':'Gru', 'DecBottom':-57.0000, 'RaLeft': 22.0000, 'RaRight': 23.3333 }
  , { 'ConciseName':'Hor', 'DecBottom':-57.5000, 'RaLeft':  3.2000, 'RaRight':  3.5000 }
  , { 'ConciseName':'Pic', 'DecBottom':-57.5000, 'RaLeft':  5.0000, 'RaRight':  5.5000 }
  , { 'ConciseName':'Car', 'DecBottom':-58.0000, 'RaLeft':  6.5000, 'RaRight':  6.8333 }
  , { 'ConciseName':'Phe', 'DecBottom':-58.5000, 'RaLeft':  0.0000, 'RaRight':  1.3333 }
  , { 'ConciseName':'Eri', 'DecBottom':-58.5000, 'RaLeft':  1.3333, 'RaRight':  2.1667 }
  , { 'ConciseName':'Phe', 'DecBottom':-58.5000, 'RaLeft': 23.3333, 'RaRight': 24.0000 }
  , { 'ConciseName':'Dor', 'DecBottom':-59.0000, 'RaLeft':  4.3333, 'RaRight':  4.5833 }
  , { 'ConciseName':'Nor', 'DecBottom':-60.0000, 'RaLeft': 15.3333, 'RaRight': 16.4208 }
  , { 'ConciseName':'Ind', 'DecBottom':-60.0000, 'RaLeft': 20.3333, 'RaRight': 21.3333 }
  , { 'ConciseName':'Pic', 'DecBottom':-61.0000, 'RaLeft':  5.5000, 'RaRight':  6.0000 }
  , { 'ConciseName':'Cir', 'DecBottom':-61.0000, 'RaLeft': 15.1667, 'RaRight': 15.3333 }
  , { 'ConciseName':'Ara', 'DecBottom':-61.0000, 'RaLeft': 16.4208, 'RaRight': 16.5833 }
  , { 'ConciseName':'Cir', 'DecBottom':-63.5833, 'RaLeft': 14.9167, 'RaRight': 15.1667 }
  , { 'ConciseName':'Ara', 'DecBottom':-63.5833, 'RaLeft': 16.5833, 'RaRight': 16.7500 }
  , { 'ConciseName':'Pic', 'DecBottom':-64.0000, 'RaLeft':  6.0000, 'RaRight':  6.8333 }
  , { 'ConciseName':'Car', 'DecBottom':-64.0000, 'RaLeft':  6.8333, 'RaRight':  9.0333 }
  , { 'ConciseName':'Cen', 'DecBottom':-64.0000, 'RaLeft': 11.2500, 'RaRight': 11.8333 }
  , { 'ConciseName':'Cru', 'DecBottom':-64.0000, 'RaLeft': 11.8333, 'RaRight': 12.8333 }
  , { 'ConciseName':'Cen', 'DecBottom':-64.0000, 'RaLeft': 12.8333, 'RaRight': 14.5333 }
  , { 'ConciseName':'Cir', 'DecBottom':-65.0000, 'RaLeft': 13.5000, 'RaRight': 13.6667 }
  , { 'ConciseName':'Ara', 'DecBottom':-65.0000, 'RaLeft': 16.7500, 'RaRight': 16.8333 }
  , { 'ConciseName':'Hor', 'DecBottom':-67.5000, 'RaLeft':  2.1667, 'RaRight':  3.2000 }
  , { 'ConciseName':'Ret', 'DecBottom':-67.5000, 'RaLeft':  3.2000, 'RaRight':  4.5833 }
  , { 'ConciseName':'Cir', 'DecBottom':-67.5000, 'RaLeft': 14.7500, 'RaRight': 14.9167 }
  , { 'ConciseName':'Ara', 'DecBottom':-67.5000, 'RaLeft': 16.8333, 'RaRight': 17.5000 }
  , { 'ConciseName':'Pav', 'DecBottom':-67.5000, 'RaLeft': 17.5000, 'RaRight': 18.0000 }
  , { 'ConciseName':'Tuc', 'DecBottom':-67.5000, 'RaLeft': 22.0000, 'RaRight': 23.3333 }
  , { 'ConciseName':'Dor', 'DecBottom':-70.0000, 'RaLeft':  4.5833, 'RaRight':  6.5833 }
  , { 'ConciseName':'Cir', 'DecBottom':-70.0000, 'RaLeft': 13.6667, 'RaRight': 14.7500 }
  , { 'ConciseName':'TrA', 'DecBottom':-70.0000, 'RaLeft': 14.7500, 'RaRight': 17.0000 }
  , { 'ConciseName':'Tuc', 'DecBottom':-75.0000, 'RaLeft':  0.0000, 'RaRight':  1.3333 }
  , { 'ConciseName':'Hyi', 'DecBottom':-75.0000, 'RaLeft':  3.5000, 'RaRight':  4.5833 }
  , { 'ConciseName':'Vol', 'DecBottom':-75.0000, 'RaLeft':  6.5833, 'RaRight':  9.0333 }
  , { 'ConciseName':'Car', 'DecBottom':-75.0000, 'RaLeft':  9.0333, 'RaRight': 11.2500 }
  , { 'ConciseName':'Mus', 'DecBottom':-75.0000, 'RaLeft': 11.2500, 'RaRight': 13.6667 }
  , { 'ConciseName':'Pav', 'DecBottom':-75.0000, 'RaLeft': 18.0000, 'RaRight': 21.3333 }
  , { 'ConciseName':'Ind', 'DecBottom':-75.0000, 'RaLeft': 21.3333, 'RaRight': 23.3333 }
  , { 'ConciseName':'Tuc', 'DecBottom':-75.0000, 'RaLeft': 23.3333, 'RaRight': 24.0000 }
  , { 'ConciseName':'Tuc', 'DecBottom':-76.0000, 'RaLeft':  0.7500, 'RaRight':  1.3333 }
  , { 'ConciseName':'Hyi', 'DecBottom':-82.5000, 'RaLeft':  0.0000, 'RaRight':  3.5000 }
  , { 'ConciseName':'Cha', 'DecBottom':-82.5000, 'RaLeft':  7.6667, 'RaRight': 13.6667 }
  , { 'ConciseName':'Aps', 'DecBottom':-82.5000, 'RaLeft': 13.6667, 'RaRight': 18.0000 }
  , { 'ConciseName':'Men', 'DecBottom':-85.0000, 'RaLeft':  3.5000, 'RaRight':  7.6667 }
  , { 'ConciseName':'Oct', 'DecBottom':-90.0000, 'RaLeft':  0.0000, 'RaRight': 24.0000 }
];

var ConstellationByConciseName = {
    'And' : { 'FullName':'Andromeda'              , 'PossessiveName':'Andromedae'              }
  , 'Ant' : { 'FullName':'Antila'                 , 'PossessiveName':'Antliae'                 }
  , 'Aps' : { 'FullName':'Apus'                   , 'PossessiveName':'Apodis'                  }
  , 'Aql' : { 'FullName':'Aquila'                 , 'PossessiveName':'Aquilae'                 }
  , 'Aqr' : { 'FullName':'Aquarius'               , 'PossessiveName':'Aquarii'                 }
  , 'Ara' : { 'FullName':'Ara'                    , 'PossessiveName':'Arae'                    }
  , 'Ari' : { 'FullName':'Aries'                  , 'PossessiveName':'Arietis'                 }
  , 'Aur' : { 'FullName':'Auriga'                 , 'PossessiveName':'Aurigae'                 }
  , 'Boo' : { 'FullName':'Bootes'                 , 'PossessiveName':'Bootis'                  }
  , 'Cae' : { 'FullName':'Caelum'                 , 'PossessiveName':'Caeli'                   }
  , 'Cam' : { 'FullName':'Camelopardis'           , 'PossessiveName':'Camelopardalis'          }
  , 'Cap' : { 'FullName':'Capricornus'            , 'PossessiveName':'Capricorni'              }
  , 'Car' : { 'FullName':'Carina'                 , 'PossessiveName':'Carinae'                 }
  , 'Cas' : { 'FullName':'Cassiopeia'             , 'PossessiveName':'Cassiopeiae'             }
  , 'Cen' : { 'FullName':'Centaurus'              , 'PossessiveName':'Centauri'                }
  , 'Cep' : { 'FullName':'Cepheus'                , 'PossessiveName':'Cephei'                  }
  , 'Cet' : { 'FullName':'Cetus'                  , 'PossessiveName':'Ceti'                    }
  , 'Cha' : { 'FullName':'Chamaeleon'             , 'PossessiveName':'Chamaeleontis'           }
  , 'Cir' : { 'FullName':'Circinus'               , 'PossessiveName':'Circini'                 }
  , 'CMa' : { 'FullName':'Canis Major'            , 'PossessiveName':'Canis Majoris'           }
  , 'CMi' : { 'FullName':'Canis Minor'            , 'PossessiveName':'Canis Minoris'           }
  , 'Cnc' : { 'FullName':'Cancer'                 , 'PossessiveName':'Cancri'                  }
  , 'Col' : { 'FullName':'Columba'                , 'PossessiveName':'Columbae'                }
  , 'Com' : { 'FullName':'Coma Berenices'         , 'PossessiveName':'Comae Berenices'         }
  , 'CrA' : { 'FullName':'Corona Australis'       , 'PossessiveName':'Coronae Austrinae'       }
  , 'CrB' : { 'FullName':'Corona Borealis'        , 'PossessiveName':'Coronae Borealis'        }
  , 'Crt' : { 'FullName':'Crater'                 , 'PossessiveName':'Crateris'                }
  , 'Cru' : { 'FullName':'Crux'                   , 'PossessiveName':'Crucis'                  }
  , 'Crv' : { 'FullName':'Corvus'                 , 'PossessiveName':'Corvi'                   }
  , 'CVn' : { 'FullName':'Canes Venatici'         , 'PossessiveName':'Canum Venaticorum'       }
  , 'Cyg' : { 'FullName':'Cygnus'                 , 'PossessiveName':'Cygni'                   }
  , 'Del' : { 'FullName':'Delphinus'              , 'PossessiveName':'Delphini'                }
  , 'Dor' : { 'FullName':'Dorado'                 , 'PossessiveName':'Doradus'                 }
  , 'Dra' : { 'FullName':'Draco'                  , 'PossessiveName':'Draconis'                }
  , 'Equ' : { 'FullName':'Equuleus'               , 'PossessiveName':'Equulei'                 }
  , 'Eri' : { 'FullName':'Eridanus'               , 'PossessiveName':'Eridani'                 }
  , 'For' : { 'FullName':'Fornax'                 , 'PossessiveName':'Fornacis'                }
  , 'Gem' : { 'FullName':'Gemini'                 , 'PossessiveName':'Geminorum'               }
  , 'Gru' : { 'FullName':'Grus'                   , 'PossessiveName':'Gruis'                   }
  , 'Her' : { 'FullName':'Hercules'               , 'PossessiveName':'Herculis'                }
  , 'Hor' : { 'FullName':'Horologium'             , 'PossessiveName':'Horologii'               }
  , 'Hya' : { 'FullName':'Hydra'                  , 'PossessiveName':'Hydrae'                  }
  , 'Hyi' : { 'FullName':'Hydrus'                 , 'PossessiveName':'Hydri'                   }
  , 'Ind' : { 'FullName':'Indus'                  , 'PossessiveName':'Indi'                    }
  , 'Lac' : { 'FullName':'Lacerta'                , 'PossessiveName':'Lacertae'                }
  , 'Leo' : { 'FullName':'Leo'                    , 'PossessiveName':'Leonis'                  }
  , 'Lep' : { 'FullName':'Lepus'                  , 'PossessiveName':'Leporis'                 }
  , 'Lib' : { 'FullName':'Libra'                  , 'PossessiveName':'Librae'                  }
  , 'LMi' : { 'FullName':'Leo Minor'              , 'PossessiveName':'Leonis Minoris'          }
  , 'Lup' : { 'FullName':'Lupus'                  , 'PossessiveName':'Lupi'                    }
  , 'Lyn' : { 'FullName':'Lynx'                   , 'PossessiveName':'Lyncis'                  }
  , 'Lyr' : { 'FullName':'Lyra'                   , 'PossessiveName':'Lyrae'                   }
  , 'Men' : { 'FullName':'Mensa'                  , 'PossessiveName':'Mensae'                  }
  , 'Mic' : { 'FullName':'Microscopium'           , 'PossessiveName':'Microscopii'             }
  , 'Mon' : { 'FullName':'Monoceros'              , 'PossessiveName':'Monocerotis'             }
  , 'Mus' : { 'FullName':'Musca'                  , 'PossessiveName':'Muscae'                  }
  , 'Nor' : { 'FullName':'Norma'                  , 'PossessiveName':'Normae'                  }
  , 'Oct' : { 'FullName':'Octans'                 , 'PossessiveName':'Octantis'                }
  , 'Oph' : { 'FullName':'Ophiuchus'              , 'PossessiveName':'Ophiuchi'                }
  , 'Ori' : { 'FullName':'Orion'                  , 'PossessiveName':'Orionis'                 }
  , 'Pav' : { 'FullName':'Pavo'                   , 'PossessiveName':'Pavonis'                 }
  , 'Peg' : { 'FullName':'Pegasus'                , 'PossessiveName':'Pegasi'                  }
  , 'Per' : { 'FullName':'Perseus'                , 'PossessiveName':'Persei'                  }
  , 'Phe' : { 'FullName':'Phoenix'                , 'PossessiveName':'Phoenicis'               }
  , 'Pic' : { 'FullName':'Pictor'                 , 'PossessiveName':'Pictoris'                }
  , 'PsA' : { 'FullName':'Pisces Austrinus'       , 'PossessiveName':'Piscis Austrini'         }
  , 'Psc' : { 'FullName':'Pisces'                 , 'PossessiveName':'Piscium'                 }
  , 'Pup' : { 'FullName':'Puppis'                 , 'PossessiveName':'Puppis'                  }
  , 'Pyx' : { 'FullName':'Pyxis'                  , 'PossessiveName':'Pyxidis'                 }
  , 'Ret' : { 'FullName':'Reticulum'              , 'PossessiveName':'Reticuli'                }
  , 'Scl' : { 'FullName':'Sculptor'               , 'PossessiveName':'Sculptoris'              }
  , 'Sco' : { 'FullName':'Scorpius'               , 'PossessiveName':'Scorpii'                 }
  , 'Sct' : { 'FullName':'Scutum'                 , 'PossessiveName':'Scuti'                   }
  , 'Ser' : { 'FullName':'Serpens'                , 'PossessiveName':'Serpentis'               }
  , 'Sex' : { 'FullName':'Sextans'                , 'PossessiveName':'Sextantis'               }
  , 'Sge' : { 'FullName':'Sagitta'                , 'PossessiveName':'Sagittae'                }
  , 'Sgr' : { 'FullName':'Sagittarius'            , 'PossessiveName':'Sagittarii'              }
  , 'Tau' : { 'FullName':'Taurus'                 , 'PossessiveName':'Tauri'                   }
  , 'Tel' : { 'FullName':'Telescopium'            , 'PossessiveName':'Telescopii'              }
  , 'TrA' : { 'FullName':'Triangulum Australe'    , 'PossessiveName':'Trianguli Australis'     }
  , 'Tri' : { 'FullName':'Triangulum'             , 'PossessiveName':'Trianguli'               }
  , 'Tuc' : { 'FullName':'Tucana'                 , 'PossessiveName':'Tucana'                  }
  , 'UMa' : { 'FullName':'Ursa Major'             , 'PossessiveName':'Ursae Majoris'           }
  , 'UMi' : { 'FullName':'Ursa Minor'             , 'PossessiveName':'Ursae Minoris'           }
  , 'Vel' : { 'FullName':'Vela'                   , 'PossessiveName':'Velorum'                 }
  , 'Vir' : { 'FullName':'Virgo'                  , 'PossessiveName':'Virginis'                }
  , 'Vol' : { 'FullName':'Volans'                 , 'PossessiveName':'Volantis'                }
  , 'Vul' : { 'FullName':'Vulpecula'              , 'PossessiveName':'Vulpeculae'              }
};

function FindConstellation(ra,dec)
{
    for (var i=0; i < ConstellationEdgeArray.length; ++i) {
        var e = ConstellationEdgeArray[i];
        if ((e.DecBottom <= dec) && (e.RaRight > ra) && (e.RaLeft <= ra)) {
            var c = ConstellationByConciseName[e.ConciseName];
            return { 'ConciseName':e.ConciseName, 'FullName':c.FullName, 'PossessiveName':c.PossessiveName };
        }
    }
    return null;    // not found!
}


// end of file  Constellation.js
